### PR TITLE
Default source value for setting

### PR DESCRIPTION
**Pull request by mishantrop**
Fixed error when saving setting.

### Related issue(s)/PR(s)
https://github.com/modmore/ClientConfig/issues/129

### CODE REVIEW

**Comment by Mark-H** [comment]
Similar to #127 but this fix seems simpler 👍

**Comment by mishantrop** [comment]
What is the purpose of this field (source)?

**Comment by Mark-H** [comment]
Used for the image field type

**Comment by mishantrop** [comment]
I was not using this type (Image) in ClientConfig before, but my solution works for me. 
Media Source is empty by default (even before my patch).

**Comment by Mark-H** [comment]
Thanks @mishantrop!

**Pull request merged**
